### ISSUE TITLE
More specific on Linux distribution

### ISSUE THREAD

**Issue by eagleoflqj** [radareorg/cutter.re#11]
On building page, there's "On some Linux distributions, all of these packages can be installed with this single command". Maybe "some" should be "Debian-based".
Moreover, build-essential isn't available on Arch-based Linux, eg Manjaro. It should be replaced by base-devel.

**Comment by ITAYC0HEN** [comment]
Good points! Thank you :) 
would you like to help us by sending a Pull Request with this information, in a way that will be understood by other users?
